category:
    #  we want to retain this for the front-end
    path: /category
    component: ./src/apps/Categories/CategoryView.vue

category-detail:
    path: /tag/view/:category
    component: ./src/apps/Categories/CategoryView.vue

content:
    #  we want to retain this for the front-end
    path: /content
    component: ./src/apps/Content/ContentView.vue

content-detail:
    path: /:slug
    component: ./src/apps/Content/ContentView.vue

resource-based-content:
    #  for some reason this content is located here
    path: /resource/:resource
    component: ./src/apps/Content/ContentView.vue

login:
    path: /profile/login
    component: ./src/apps/Profile/FormView.vue

logout:
    path: /profile/logout
    component: ./src/apps/Profile/FormView.vue

# not sure this is needed at the monment?
profile-detail:
    path: /profile/:slug
    component: ./src/apps/Profile/FormView.vue

profile-subdetail:
    path: /profile/:slug/:subslug
    component: ./src/apps/Profile/FormView.vue

#  we want to retain this for the front-end
profile-form:
    path: /form
    component: ./src/apps/Profile/FormView.vue



# analytics-detail:
#     name: /analytics/:slug
#     component: ./src/apps/Analytics/AnalyticsView.vue
